### ISSUE TITLE
Doesn't work on Mac OSX 10.6.8

### ISSUE THREAD

**Issue by filmo** [michaelficarra/tumblr-scraper#1]
```
user$ ruby scrape.rb  http://domainToScrape.tumblr.com
Scraping http://domainToScrape.tumblr.com
scrape.rb:16: undefined method `path' for ".":String (NoMethodError)
    from scrape.rb:24:in `call'
    from scrape.rb:24
    from scrape.rb:13:in `each'
    from scrape.rb:13
```

**Comment by michaelficarra** [comment]
Try that. I have to warn you, this project was written very quickly and only tested once on a single tumblr blog. It may not work at all, who knows.
